site_name: 智行天下

theme:
  name: material
  language: zh
  logo: images/logo.png
  favicon: images/favicon.png
  font:
    text: Source Han Sans SC,Noto Sans CJK SC,Microsoft Yahei,sans,Roboto

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kisa747
#  是否显示Made with Material for MkDocs
#  generator: false
# 版权声明
copyright: Copyright &copy; 2022 - 2022 kisa747
# 显示仓库地址
repo_url: https://github.com/kisa747/notebook

markdown_extensions:
  # 注释标题
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# 代码标题
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # 表格
  - tables

  # 公式
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # 支持公式需要的 js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



